name: pidm
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - aom=3.5.0
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.4.26
  - cairo=1.16.0
  - certifi=2025.4.26
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - contourpy=1.3.1
  - cycler=0.11.0
  - dav1d=1.2.1
  - dill=0.4.0
  - expat=2.7.1
  - ffmpeg=5.1.2
  - filelock=3.17.0
  - findiff=0.12.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.55.3
  - freetype=2.13.3
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.10
  - gettext=0.24.1
  - gettext-tools=0.24.1
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.7.9
  - graphite2=1.3.14
  - harfbuzz=6.0.0
  - hdf5=1.14.0
  - icu=72.1
  - idna=3.7
  - jasper=2.0.33
  - jinja2=3.1.6
  - jpeg=9e
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.15
  - leptonica=1.82.0
  - lerc=4.0.0
  - libaec=1.1.3
  - libarchive=3.6.2
  - libasprintf=0.24.1
  - libasprintf-devel=0.24.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.8.0
  - libcxx=20.1.4
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.4
  - libgettextpo=0.24.1
  - libgettextpo-devel=0.24.1
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.78.4
  - libiconv=1.18
  - libidn2=2.3.8
  - libintl=0.24.1
  - libintl-devel=0.24.1
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.58.0
  - libogg=1.3.5
  - libopenblas=0.3.29
  - libopencv=4.7.0
  - libopus=1.3.1
  - libpng=1.6.39
  - libprotobuf=3.21.12
  - librsvg=2.56.3
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libtasn1=4.20.0
  - libtheora=1.1.1
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.11.5
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - lzo=2.10
  - markupsafe=3.0.2
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.9.1
  - networkx=3.4.2
  - numpy=1.26.4
  - numpy-base=1.26.4
  - opencv=4.7.0
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=3.5.0
  - p11-kit=0.24.1
  - packaging=24.2
  - pandas=2.2.3
  - pango=1.50.14
  - pcre2=10.42
  - pillow=9.4.0
  - pip=25.1
  - pixman=0.40.0
  - pthread-stubs=0.4
  - py-opencv=4.7.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytorch=2.0.1
  - pytz=2025.2
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - scipy=1.15.2
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.45.3
  - svt-av1=1.4.1
  - sympy=1.13.3
  - tesseract=5.2.0
  - tk=8.6.14
  - torchaudio=2.0.2
  - torchvision=0.15.2
  - tornado=6.4.2
  - tqdm=4.65.0
  - typing_extensions=4.12.2
  - tzdata=2025b
  - unicodedata2=15.1.0
  - urllib3=2.3.0
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - appdirs==1.4.4
      - click==8.1.8
      - docker-pycreds==0.4.0
      - easygui==0.98.3
      - einops==0.6.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - imageio==2.37.0
      - meshio==3.0.0
      - pathtools==0.1.2
      - protobuf==4.25.7
      - psutil==7.0.0
      - sentry-sdk==2.27.0
      - setproctitle==1.3.6
      - smmap==5.0.2
      - solidspy==1.1.0.post1
      - wandb==0.15.2
